// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuzzuleQuestion.DbContex;

#nullable disable

namespace PuzzuleQuestion.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220428054932_InitialMigration2")]
    partial class InitialMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PuzzuleQuestion.Model.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Answer1")
                        .HasColumnType("int");

                    b.Property<int>("Answer10")
                        .HasColumnType("int");

                    b.Property<int>("Answer2")
                        .HasColumnType("int");

                    b.Property<int>("Answer3")
                        .HasColumnType("int");

                    b.Property<int>("Answer4")
                        .HasColumnType("int");

                    b.Property<int>("Answer5")
                        .HasColumnType("int");

                    b.Property<int>("Answer6")
                        .HasColumnType("int");

                    b.Property<int>("Answer7")
                        .HasColumnType("int");

                    b.Property<int>("Answer8")
                        .HasColumnType("int");

                    b.Property<int>("Answer9")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AnswerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("PuzzuleQuestion.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PuzzuleQuestion.Model.Answer", b =>
                {
                    b.HasOne("PuzzuleQuestion.Model.User", null)
                        .WithOne("Answer")
                        .HasForeignKey("PuzzuleQuestion.Model.Answer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PuzzuleQuestion.Model.User", b =>
                {
                    b.Navigation("Answer");
                });
#pragma warning restore 612, 618
        }
    }
}
